left_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.1
  goal_position_tolerance: 0.1
  goal_orientation_tolerance: 0.1
right_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.1
  goal_position_tolerance: 0.1
  goal_orientation_tolerance: 0.1
# pelvis:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   goal_joint_tolerance: 0.0001
#   goal_position_tolerance: 0.0001
#   goal_orientation_tolerance: 0.001
# body_movement:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   goal_joint_tolerance: 0.0001
#   goal_position_tolerance: 0.0001
#   goal_orientation_tolerance: 0.001
# upper_body:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   goal_joint_tolerance: 0.0001
#   goal_position_tolerance: 0.0001
#   goal_orientation_tolerance: 0.001